export const COLOR = {
    MAIN_ORANGE: "#FE8C12",

    BUTTON_BLACK: "#282A29",
    BORDERSHADOW_BLACK: "#AAAAAA",
    
    BORDERSHADOW_BLACKLIGHT: "#BEBDBD",
    TEXT_LIGHTGRAY:"#6A6A6A",

    
    NAVER_GREEN:"#03C75A",

    BACKGROUND_DEFAULT : "#E7E7E7",
     BACKGROUND_LIGHTGRAY : "#F2F4F6",
     BACKGROUND_WHITE_DOWN : "#FAFAFA",
     CARDBACKGROUND_WHITE:"#E4E4E4",

     MAINICONBGCOLOR_RED:"#E5DDD5"
}